
[versions]
ben-manes-versions = "0.54.0"
commons-cli = "1.11.0"
commons-math3 = "3.6.1"
guava = "33.6.0-jre"
jackson = "2.22.1"
jjwt = "0.13.0"
junit-jupiter = "6.1.2"
mqtt-paho = "1.2.5"
slf4j = "2.1.0-alpha1"

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes-versions" }

[libraries]
commons-cli = { module = "commons-cli:commons-cli", version.ref = "commons-cli" }
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }

guava = { module = "com.google.guava:guava", version.ref = "guava" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }

jjwt = { module = "io.jsonwebtoken:jjwt", version.ref = "jjwt" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

mqtt-paho-v5-client = { module = "org.eclipse.paho:org.eclipse.paho.mqttv5.client", version.ref = "mqtt-paho" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

